from skidl import Pin, Part, Alias, SchLib, SKIDL, TEMPLATE

SKIDL_lib_version = '0.0.1'

cube_controller_lib = SchLib(tool=SKIDL).add_parts(*[
        Part(**{ 'name':'Conn_01x03', 'dest':TEMPLATE, 'tool':SKIDL, 'F0':'J', 'keywords':'connector', 'F1':'Conn_01x03', 'datasheet':'~', 'description':'Generic connector, single row, 01x03, script generated (kicad-library-utils/schlib/autogen/connector/)', 'ref_prefix':'J', 'num_units':1, 'fplist':['Connector*:*_1x??_*'], 'do_erc':True, 'footprint':'gkl_conn:3P_Battery_Connector', 'pins':[
            Pin(num='1',name='Pin_1',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='2',name='Pin_2',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='3',name='Pin_3',func=Pin.types.PASSIVE,do_erc=True)] }),
        Part(**{ 'name':'LTC4367', 'dest':TEMPLATE, 'tool':SKIDL, 'F0':'U', 'F1':'LTC4367', 'ref_prefix':'U', 'num_units':1, 'do_erc':True, 'footprint':'Package_DFN_QFN:DFN-8-1EP_3x3mm_P0.5mm_EP1.66x2.38mm', 'pins':[
            Pin(num='1',name='VIN',func=Pin.types.INPUT,do_erc=True),
            Pin(num='2',name='UV',func=Pin.types.INPUT,do_erc=True),
            Pin(num='3',name='OV',func=Pin.types.INPUT,do_erc=True),
            Pin(num='4',name='GND',func=Pin.types.INPUT,do_erc=True),
            Pin(num='5',name='~SHDN',func=Pin.types.INPUT,do_erc=True),
            Pin(num='6',name='~FAULT',func=Pin.types.INPUT,do_erc=True),
            Pin(num='7',name='VOUT',func=Pin.types.INPUT,do_erc=True),
            Pin(num='8',name='GATE',func=Pin.types.INPUT,do_erc=True)] }),
        Part(**{ 'name':'AON7804', 'dest':TEMPLATE, 'tool':SKIDL, 'F0':'U', 'F1':'AON7804', 'ref_prefix':'U', 'num_units':1, 'do_erc':True, 'footprint':'gkl_housings_dfn:DFN3X3_8L_EP2_P', 'pins':[
            Pin(num='1',name='D',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='2',name='S',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='3',name='G',func=Pin.types.INPUT,do_erc=True),
            Pin(num='4',name='D',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='5',name='S',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='6',name='G',func=Pin.types.INPUT,do_erc=True)] }),
        Part(**{ 'name':'R', 'dest':TEMPLATE, 'tool':SKIDL, 'F0':'R', 'keywords':'R res resistor', 'F1':'R', 'datasheet':'~', 'description':'Resistor', 'ref_prefix':'R', 'num_units':1, 'fplist':['R_*'], 'do_erc':True, 'footprint':'Resistor_SMD:R_0402_1005Metric', 'pins':[
            Pin(num='1',name='~',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='2',name='~',func=Pin.types.PASSIVE,do_erc=True)] }),
        Part(**{ 'name':'TPS62135', 'dest':TEMPLATE, 'tool':SKIDL, 'F0':'U', 'F1':'TPS62135', 'ref_prefix':'U', 'num_units':1, 'do_erc':True, 'footprint':'gkl_misc:VQFN-11_3x2mm_P0.5mm', 'pins':[
            Pin(num='1',name='VIN',func=Pin.types.PWRIN,do_erc=True),
            Pin(num='10',name='MODE',func=Pin.types.INPUT,do_erc=True),
            Pin(num='11',name='VSEL',func=Pin.types.INPUT,do_erc=True),
            Pin(num='2',name='SW',func=Pin.types.PWROUT,do_erc=True),
            Pin(num='3',name='GND',func=Pin.types.PWRIN,do_erc=True),
            Pin(num='4',name='FB2',func=Pin.types.OUTPUT,do_erc=True),
            Pin(num='5',name='FB',func=Pin.types.OUTPUT,do_erc=True),
            Pin(num='6',name='VOS',func=Pin.types.INPUT,do_erc=True),
            Pin(num='7',name='PG',func=Pin.types.OUTPUT,do_erc=True),
            Pin(num='8',name='EN',func=Pin.types.INPUT,do_erc=True),
            Pin(num='9',name='SS/TR',func=Pin.types.INPUT,do_erc=True)] }),
        Part(**{ 'name':'L', 'dest':TEMPLATE, 'tool':SKIDL, 'F0':'L', 'keywords':'inductor choke coil reactor magnetic', 'F1':'L', 'datasheet':'~', 'description':'Inductor', 'ref_prefix':'L', 'num_units':1, 'fplist':['Choke_*', '*Coil*', 'Inductor_*', 'L_*'], 'do_erc':True, 'footprint':'Inductor_SMD:L_Coilcraft_XxL4020', 'pins':[
            Pin(num='1',name='1',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='2',name='2',func=Pin.types.PASSIVE,do_erc=True)] }),
        Part(**{ 'name':'C', 'dest':TEMPLATE, 'tool':SKIDL, 'F0':'C', 'keywords':'cap capacitor', 'F1':'C', 'datasheet':'~', 'description':'Unpolarized capacitor', 'ref_prefix':'C', 'num_units':1, 'fplist':['C_*'], 'do_erc':True, 'footprint':'Capacitor_SMD:C_0603_1608Metric', 'pins':[
            Pin(num='1',name='~',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='2',name='~',func=Pin.types.PASSIVE,do_erc=True)] }),
        Part(**{ 'name':'TPS561201', 'dest':TEMPLATE, 'tool':SKIDL, 'F0':'U', 'F1':'TPS561201', 'ref_prefix':'U', 'num_units':1, 'do_erc':True, 'footprint':'Package_TO_SOT_SMD:TSOT-23-6', 'pins':[
            Pin(num='1',name='GND',func=Pin.types.PWRIN,do_erc=True),
            Pin(num='2',name='SW',func=Pin.types.PWROUT,do_erc=True),
            Pin(num='3',name='VIN',func=Pin.types.PWRIN,do_erc=True),
            Pin(num='4',name='VFB',func=Pin.types.INPUT,do_erc=True),
            Pin(num='5',name='EN',func=Pin.types.INPUT,do_erc=True),
            Pin(num='6',name='VBST',func=Pin.types.INPUT,do_erc=True)] }),
        Part(**{ 'name':'NP115-2.5', 'dest':TEMPLATE, 'tool':SKIDL, 'F3':'http://www.onsemi.com/pub/Collateral/NCP167-D.PDF', 'F0':'U', 'F1':'NCP167', 'ref_prefix':'U', 'num_units':1, 'do_erc':True, 'footprint':'gkl_housings_son:X2SON_4_1.0x1.0mm', 'pins':[
            Pin(num='1',name='OUT',func=Pin.types.INPUT,do_erc=True),
            Pin(num='2',name='GND',func=Pin.types.INPUT,do_erc=True),
            Pin(num='3',name='EN',func=Pin.types.INPUT,do_erc=True),
            Pin(num='4',name='IN',func=Pin.types.INPUT,do_erc=True)] }),
        Part(**{ 'name':'NP115-1.2', 'dest':TEMPLATE, 'tool':SKIDL, 'F3':'http://www.onsemi.com/pub/Collateral/NCP167-D.PDF', 'F0':'U', 'F1':'NCP167', 'ref_prefix':'U', 'num_units':1, 'do_erc':True, 'footprint':'gkl_housings_son:X2SON_4_1.0x1.0mm', 'pins':[
            Pin(num='1',name='OUT',func=Pin.types.INPUT,do_erc=True),
            Pin(num='2',name='GND',func=Pin.types.INPUT,do_erc=True),
            Pin(num='3',name='EN',func=Pin.types.INPUT,do_erc=True),
            Pin(num='4',name='IN',func=Pin.types.INPUT,do_erc=True)] }),
        Part(**{ 'name':'Ferrite_Bead_Small', 'dest':TEMPLATE, 'tool':SKIDL, 'F0':'FB', 'keywords':'L ferrite bead inductor filter', 'F1':'Ferrite_Bead_Small', 'datasheet':'~', 'description':'Ferrite bead, small symbol', 'ref_prefix':'FB', 'num_units':1, 'fplist':['Inductor_*', 'L_*', '*Ferrite*'], 'do_erc':True, 'footprint':'Inductor_SMD:L_0402_1005Metric', 'pins':[
            Pin(num='1',name='~',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='2',name='~',func=Pin.types.PASSIVE,do_erc=True)] }),
        Part(**{ 'name':'CP1', 'dest':TEMPLATE, 'tool':SKIDL, 'F0':'C', 'keywords':'cap capacitor', 'F1':'CP1', 'datasheet':'~', 'description':'Polarized capacitor, US symbol', 'ref_prefix':'C', 'num_units':1, 'fplist':['CP_*'], 'do_erc':True, 'footprint':'Capacitor_SMD:CP_Elec_5x3.9', 'pins':[
            Pin(num='1',name='~',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='2',name='~',func=Pin.types.PASSIVE,do_erc=True)] }),
        Part(**{ 'name':'LED_ARGB', 'dest':TEMPLATE, 'tool':SKIDL, 'F0':'D', 'keywords':'LED RGB diode', 'F1':'LED_ARGB', 'datasheet':'~', 'description':'RGB LED, anode/red/green/blue', 'ref_prefix':'D', 'num_units':1, 'fplist':['LED*', 'LED_SMD:*', 'LED_THT:*'], 'do_erc':True, 'footprint':'gkl_led:led_rbag_1515', 'pins':[
            Pin(num='1',name='A',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='2',name='RK',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='3',name='GK',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='4',name='BK',func=Pin.types.PASSIVE,do_erc=True)] }),
        Part(**{ 'name':'ATSAMD51G19A', 'dest':TEMPLATE, 'tool':SKIDL, 'F0':'U', 'F1':'ATSAMD51G19A', 'ref_prefix':'U', 'num_units':1, 'do_erc':True, 'footprint':'Package_DFN_QFN:QFN-48-1EP_7x7mm_P0.5mm_EP5.15x5.15mm', 'pins':[
            Pin(num='1',name='PA00',func=Pin.types.INPUT,do_erc=True),
            Pin(num='10',name='PA05',func=Pin.types.INPUT,do_erc=True),
            Pin(num='11',name='PA06',func=Pin.types.INPUT,do_erc=True),
            Pin(num='12',name='PA07',func=Pin.types.INPUT,do_erc=True),
            Pin(num='13',name='PA08',func=Pin.types.INPUT,do_erc=True),
            Pin(num='14',name='PA09',func=Pin.types.INPUT,do_erc=True),
            Pin(num='15',name='PA10',func=Pin.types.INPUT,do_erc=True),
            Pin(num='16',name='PA11',func=Pin.types.INPUT,do_erc=True),
            Pin(num='17',name='VDDIO',func=Pin.types.INPUT,do_erc=True),
            Pin(num='18',name='GND',func=Pin.types.INPUT,do_erc=True),
            Pin(num='19',name='PB10',func=Pin.types.INPUT,do_erc=True),
            Pin(num='2',name='PA01',func=Pin.types.INPUT,do_erc=True),
            Pin(num='20',name='PB11',func=Pin.types.INPUT,do_erc=True),
            Pin(num='21',name='PA12',func=Pin.types.INPUT,do_erc=True),
            Pin(num='22',name='PA13',func=Pin.types.INPUT,do_erc=True),
            Pin(num='23',name='PA14',func=Pin.types.INPUT,do_erc=True),
            Pin(num='24',name='PA15',func=Pin.types.INPUT,do_erc=True),
            Pin(num='25',name='PA16',func=Pin.types.INPUT,do_erc=True),
            Pin(num='26',name='PA17',func=Pin.types.INPUT,do_erc=True),
            Pin(num='27',name='PA18',func=Pin.types.INPUT,do_erc=True),
            Pin(num='28',name='PA19',func=Pin.types.INPUT,do_erc=True),
            Pin(num='29',name='PA20',func=Pin.types.INPUT,do_erc=True),
            Pin(num='3',name='PA02',func=Pin.types.INPUT,do_erc=True),
            Pin(num='30',name='PA21',func=Pin.types.INPUT,do_erc=True),
            Pin(num='31',name='PA22',func=Pin.types.INPUT,do_erc=True),
            Pin(num='32',name='PA23',func=Pin.types.INPUT,do_erc=True),
            Pin(num='33',name='PA24',func=Pin.types.INPUT,do_erc=True),
            Pin(num='34',name='PA25',func=Pin.types.INPUT,do_erc=True),
            Pin(num='35',name='GND',func=Pin.types.INPUT,do_erc=True),
            Pin(num='36',name='VDDIO',func=Pin.types.INPUT,do_erc=True),
            Pin(num='37',name='PB22',func=Pin.types.INPUT,do_erc=True),
            Pin(num='38',name='PB23',func=Pin.types.INPUT,do_erc=True),
            Pin(num='39',name='PA27',func=Pin.types.INPUT,do_erc=True),
            Pin(num='4',name='PA03',func=Pin.types.INPUT,do_erc=True),
            Pin(num='40',name='~RESET',func=Pin.types.INPUT,do_erc=True),
            Pin(num='41',name='VDDCORE',func=Pin.types.INPUT,do_erc=True),
            Pin(num='42',name='GND',func=Pin.types.INPUT,do_erc=True),
            Pin(num='43',name='VSW',func=Pin.types.INPUT,do_erc=True),
            Pin(num='44',name='VDDIO',func=Pin.types.INPUT,do_erc=True),
            Pin(num='45',name='PA30',func=Pin.types.INPUT,do_erc=True),
            Pin(num='46',name='PA31',func=Pin.types.INPUT,do_erc=True),
            Pin(num='47',name='PB02',func=Pin.types.INPUT,do_erc=True),
            Pin(num='48',name='PB03',func=Pin.types.INPUT,do_erc=True),
            Pin(num='49',name='GND',func=Pin.types.INPUT,do_erc=True),
            Pin(num='5',name='GND',func=Pin.types.INPUT,do_erc=True),
            Pin(num='6',name='VDDANA',func=Pin.types.INPUT,do_erc=True),
            Pin(num='7',name='PB08',func=Pin.types.INPUT,do_erc=True),
            Pin(num='8',name='PB09',func=Pin.types.INPUT,do_erc=True),
            Pin(num='9',name='PA04',func=Pin.types.INPUT,do_erc=True)] }),
        Part(**{ 'name':'Crystal', 'dest':TEMPLATE, 'tool':SKIDL, 'F0':'Y', 'keywords':'quartz ceramic resonator oscillator', 'F1':'Crystal', 'datasheet':'~', 'description':'Two pin crystal', 'ref_prefix':'Y', 'num_units':1, 'fplist':['Crystal*'], 'do_erc':True, 'footprint':'Crystal:Crystal_SMD_2012-2Pin_2.0x1.2mm', 'pins':[
            Pin(num='1',name='1',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='2',name='2',func=Pin.types.PASSIVE,do_erc=True)] }),
        Part(**{ 'name':'ICE40UP5K-SG48ITR', 'dest':TEMPLATE, 'tool':SKIDL, 'F0':'U', 'keywords':'FPGA programmable logic', 'F1':'ICE40UP5K-SG48ITR', 'F2':'Package_DFN_QFN:QFN-48-1EP_7x7mm_P0.5mm_EP5.6x5.6mm', 'datasheet':'http://www.latticesemi.com/Products/FPGAandCPLD/iCE40Ultra', 'description':'iCE40 UltraPlus FPGA, 5280 LUTs, 1.2V, 48-pin QFN', 'ref_prefix':'U', 'num_units':4, 'fplist':['QFN*7x7mm*P0.5mm*EP5.6x5.6mm*'], 'do_erc':True, 'footprint':'Package_DFN_QFN:QFN-48-1EP_7x7mm_P0.5mm_EP5.15x5.15mm', 'pins':[
            Pin(num='23',name='IOT_37a',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='25',name='IOT_36b',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='26',name='IOT_39a',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='27',name='IOT_38b',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='28',name='IOT_41a',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='31',name='IOT_42b',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='32',name='IOT_43a',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='33',name='VCCIO_0',func=Pin.types.PWRIN,do_erc=True),
            Pin(num='34',name='IOT_44b',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='35',name='IOT_46b_G0',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='36',name='IOT_48b',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='37',name='IOT_45a_G1',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='38',name='IOT_50b',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='39',name='RGB0',func=Pin.types.OPENCOLL,do_erc=True),
            Pin(num='40',name='RGB1',func=Pin.types.OPENCOLL,do_erc=True),
            Pin(num='41',name='RGB2',func=Pin.types.OPENCOLL,do_erc=True),
            Pin(num='42',name='IOT_51a',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='43',name='IOT_49a',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='10',name='IOB_18a',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='11',name='IOB_20a',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='12',name='IOB_22b',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='13',name='IOB_24a',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='14',name='IOB_32a_SPI_SO',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='15',name='IOB_34a_SPI_SCK',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='16',name='IOB_35b_SPI_SS',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='17',name='IOB_33b_SPI_SI',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='18',name='IOB_31b',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='19',name='IOB_29b',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='20',name='IOB_25b_G3',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='21',name='IOB_23b',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='22',name='SPI_VCCIO1',func=Pin.types.PWRIN,do_erc=True),
            Pin(num='6',name='IOB_13b',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='7',name='CDONE',func=Pin.types.OPENCOLL,do_erc=True),
            Pin(num='8',name='~CRESET',func=Pin.types.INPUT,do_erc=True),
            Pin(num='9',name='IOB_16a',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='1',name='VCCIO_2',func=Pin.types.PWRIN,do_erc=True),
            Pin(num='2',name='IOB_6a',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='3',name='IOB_9b',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='4',name='IOB_8a',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='44',name='IOB_3b_G6',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='45',name='IOB_5b',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='46',name='IOB_0a',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='47',name='IOB_2a',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='48',name='IOB_4a',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='24',name='VPP_2V5',func=Pin.types.PWRIN,do_erc=True),
            Pin(num='29',name='VCCPLL',func=Pin.types.PWROUT,do_erc=True),
            Pin(num='30',name='VCC',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='49',name='GND',func=Pin.types.PWRIN,do_erc=True),
            Pin(num='5',name='VCC',func=Pin.types.PWRIN,do_erc=True)] }),
        Part(**{ 'name':'SN74AVC8T245PW', 'dest':TEMPLATE, 'tool':SKIDL, 'F0':'U', 'keywords':'Noninverting Bidirectional', 'F1':'SN74AVC8T245PW', 'F2':'Package_SO:TSSOP-24_4.4x7.8mm_P0.65mm', 'datasheet':'https://www.ti.com/lit/ds/symlink/sn74avc8t245.pdf', 'description':'8-Bit Dual-Supply Bus Transceiver With Configurable Voltage Translation and 3-State Outputs, TSSOP-24', 'ref_prefix':'U', 'num_units':1, 'fplist':['TSSOP*4.4x7.8mm*P0.65mm*'], 'do_erc':True, 'footprint':'Package_DFN_QFN:Texas_RGY_R-PVQFN-N24_EP2.05x3.1mm', 'pins':[
            Pin(num='1',name='VCCA',func=Pin.types.PWRIN,do_erc=True),
            Pin(num='10',name='A8',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='11',name='GND',func=Pin.types.PWRIN,do_erc=True),
            Pin(num='12',name='GND',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='13',name='GND',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='14',name='B8',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='15',name='B7',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='16',name='B6',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='17',name='B5',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='18',name='B4',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='19',name='B3',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='2',name='DIR',func=Pin.types.INPUT,do_erc=True),
            Pin(num='20',name='B2',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='21',name='B1',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='22',name='~OE',func=Pin.types.INPUT,do_erc=True),
            Pin(num='23',name='VCCB',func=Pin.types.PWRIN,do_erc=True),
            Pin(num='24',name='VCCB',func=Pin.types.PWRIN,do_erc=True),
            Pin(num='3',name='A1',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='4',name='A2',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='5',name='A3',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='6',name='A4',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='7',name='A5',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='8',name='A6',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='9',name='A7',func=Pin.types.BIDIR,do_erc=True)] }),
        Part(**{ 'name':'Conn_01x20_Shielded', 'dest':TEMPLATE, 'tool':SKIDL, 'F0':'J', 'keywords':'connector', 'F1':'Conn_01x20_Shielded', 'datasheet':'~', 'description':'Generic shielded connector, single row, 01x20, script generated (kicad-library-utils/schlib/autogen/connector/)', 'ref_prefix':'J', 'num_units':1, 'fplist':['Connector*:*_1x??-1SH*'], 'do_erc':True, 'footprint':'gkl_conn:FH12-20S-0.5SVA(54)', 'pins':[
            Pin(num='1',name='Pin_1',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='10',name='Pin_10',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='11',name='Pin_11',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='12',name='Pin_12',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='13',name='Pin_13',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='14',name='Pin_14',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='15',name='Pin_15',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='16',name='Pin_16',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='17',name='Pin_17',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='18',name='Pin_18',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='19',name='Pin_19',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='2',name='Pin_2',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='20',name='Pin_20',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='3',name='Pin_3',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='4',name='Pin_4',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='5',name='Pin_5',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='6',name='Pin_6',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='7',name='Pin_7',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='8',name='Pin_8',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='9',name='Pin_9',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='SH',name='Shield',func=Pin.types.PASSIVE,do_erc=True)] }),
        Part(**{ 'name':'Conn_02x05_Odd_Even', 'dest':TEMPLATE, 'tool':SKIDL, 'F0':'J', 'keywords':'connector', 'F1':'Conn_02x05_Odd_Even', 'datasheet':'~', 'description':'Generic connector, double row, 02x05, odd/even pin numbering scheme (row 1 odd numbers, row 2 even numbers), script generated (kicad-library-utils/schlib/autogen/connector/)', 'ref_prefix':'J', 'num_units':1, 'fplist':['Connector*:*_2x??_*'], 'do_erc':True, 'footprint':'gkl_conn:FTSH-105-XX-X-DV', 'pins':[
            Pin(num='1',name='Pin_1',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='10',name='Pin_10',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='2',name='Pin_2',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='3',name='Pin_3',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='4',name='Pin_4',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='5',name='Pin_5',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='6',name='Pin_6',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='7',name='Pin_7',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='8',name='Pin_8',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='9',name='Pin_9',func=Pin.types.PASSIVE,do_erc=True)] }),
        Part(**{ 'name':'BMX160', 'dest':TEMPLATE, 'tool':SKIDL, 'F0':'U', 'F1':'BMX160', 'ref_prefix':'U', 'num_units':1, 'do_erc':True, 'footprint':'Package_LGA:Bosch_LGA-14_3x2.5mm_P0.5mm', 'pins':[
            Pin(num='1',name='SDO',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='10',name='NC',func=Pin.types.INPUT,do_erc=True),
            Pin(num='11',name='NC',func=Pin.types.INPUT,do_erc=True),
            Pin(num='12',name='~CS',func=Pin.types.INPUT,do_erc=True),
            Pin(num='13',name='SCx',func=Pin.types.INPUT,do_erc=True),
            Pin(num='14',name='SDx',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='2',name='GND',func=Pin.types.PWRIN,do_erc=True),
            Pin(num='3',name='GND',func=Pin.types.PWRIN,do_erc=True),
            Pin(num='4',name='INT1',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='5',name='VDDIO',func=Pin.types.PWRIN,do_erc=True),
            Pin(num='6',name='GNDIO',func=Pin.types.PWRIN,do_erc=True),
            Pin(num='7',name='GND',func=Pin.types.PWRIN,do_erc=True),
            Pin(num='8',name='VDD',func=Pin.types.PWRIN,do_erc=True),
            Pin(num='9',name='INT2',func=Pin.types.BIDIR,do_erc=True)] }),
        Part(**{ 'name':'AT25SF081', 'dest':TEMPLATE, 'tool':SKIDL, 'F0':'U', 'F1':'AT25SF081', 'ref_prefix':'U', 'num_units':1, 'do_erc':True, 'footprint':'Package_SO:SOIC-8_5.23x5.23mm_P1.27mm', 'pins':[
            Pin(num='1',name='~CS',func=Pin.types.INPUT,do_erc=True),
            Pin(num='2',name='SO',func=Pin.types.INPUT,do_erc=True),
            Pin(num='3',name='~WP',func=Pin.types.INPUT,do_erc=True),
            Pin(num='4',name='GND',func=Pin.types.INPUT,do_erc=True),
            Pin(num='5',name='SI',func=Pin.types.INPUT,do_erc=True),
            Pin(num='6',name='SCK',func=Pin.types.INPUT,do_erc=True),
            Pin(num='7',name='~HOLD',func=Pin.types.INPUT,do_erc=True),
            Pin(num='8',name='VCC',func=Pin.types.INPUT,do_erc=True)] }),
        Part(**{ 'name':'USB_C_Receptacle_USB2.0', 'dest':TEMPLATE, 'tool':SKIDL, 'F0':'J', 'keywords':'usb universal serial bus type-C USB2.0', 'F1':'USB_C_Receptacle_USB2.0', 'datasheet':'https://www.usb.org/sites/default/files/documents/usb_type-c.zip', 'description':'USB 2.0-only Type-C Receptacle connector', 'ref_prefix':'J', 'num_units':1, 'fplist':['USB*C*Receptacle*'], 'do_erc':True, 'footprint':'Connector_USB:USB_C_Receptacle_Palconn_UTC16-G', 'pins':[
            Pin(num='A1',name='GND',func=Pin.types.PWRIN,do_erc=True),
            Pin(num='A12',name='GND',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='A4',name='VBUS',func=Pin.types.PWRIN,do_erc=True),
            Pin(num='A5',name='CC1',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='A6',name='D+',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='A7',name='D-',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='A8',name='SBU1',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='A9',name='VBUS',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='B1',name='GND',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='B12',name='GND',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='B4',name='VBUS',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='B5',name='CC2',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='B6',name='D+',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='B7',name='D-',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='B8',name='SBU2',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='B9',name='VBUS',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='S1',name='SHIELD',func=Pin.types.PASSIVE,do_erc=True)] }),
        Part(**{ 'name':'SW_Push', 'dest':TEMPLATE, 'tool':SKIDL, 'F0':'SW', 'keywords':'switch normally-open pushbutton push-button', 'F1':'SW_Push', 'datasheet':'~', 'description':'Push button switch, generic, two pins', 'ref_prefix':'SW', 'num_units':1, 'do_erc':True, 'footprint':'gkl_misc:EVQP4', 'pins':[
            Pin(num='1',name='1',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='2',name='2',func=Pin.types.PASSIVE,do_erc=True)] }),
        Part(**{ 'name':'LTC4413-2', 'dest':TEMPLATE, 'tool':SKIDL, 'F0':'U', 'F1':'LTC4413-2', 'ref_prefix':'U', 'num_units':1, 'do_erc':True, 'footprint':'Package_DFN_QFN:DFN-10-1EP_3x3mm_P0.5mm_EP1.65x2.38mm', 'pins':[
            Pin(num='1',name='INA',func=Pin.types.INPUT,do_erc=True),
            Pin(num='10',name='OUTA',func=Pin.types.INPUT,do_erc=True),
            Pin(num='11',name='SGND',func=Pin.types.INPUT,do_erc=True),
            Pin(num='2',name='ENBA',func=Pin.types.INPUT,do_erc=True),
            Pin(num='3',name='GND',func=Pin.types.INPUT,do_erc=True),
            Pin(num='4',name='ENBB',func=Pin.types.INPUT,do_erc=True),
            Pin(num='5',name='INB',func=Pin.types.INPUT,do_erc=True),
            Pin(num='6',name='OUTB',func=Pin.types.INPUT,do_erc=True),
            Pin(num='7',name='OVP',func=Pin.types.INPUT,do_erc=True),
            Pin(num='8',name='OVI',func=Pin.types.INPUT,do_erc=True),
            Pin(num='9',name='STAT',func=Pin.types.INPUT,do_erc=True)] }),
        Part(**{ 'name':'5.1k', 'dest':TEMPLATE, 'tool':SKIDL, 'F0':'R', 'keywords':'R res resistor', 'F1':'R', 'datasheet':'~', 'description':'Resistor', 'ref_prefix':'R', 'num_units':1, 'fplist':['R_*'], 'do_erc':True, 'footprint':'Resistor_SMD:R_0402_1005Metric', 'pins':[
            Pin(num='1',name='~',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='2',name='~',func=Pin.types.PASSIVE,do_erc=True)] })])